name: Java CI with Gradle

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  Test:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
      - name: Run Tests
        run: ./gradlew test
      - name: Generate Reports
        run: ./gradlew generateCucumberReports
      - name: Upload Test Reports
        uses: actions/upload-artifact@v3
        with:
          name: test-reports
          path: build/reports/**/*

  Code-Analysis:
    needs: Test
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
      - name: Run Static Analysis
        run: ./gradlew sonar

  Code-Quality:
    needs: Code-Analysis
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
      - name: Check Quality Gates
        run: ./gradlew sonarqube

  Build:
    needs: Code-Quality
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
      - name: Build Project
        run: ./gradlew build
      - name: Generate Documentation
        run: ./gradlew javadoc
      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-artifacts
          path: |
            build/libs/*.jar
            build/docs/javadoc/**/*

  Deploy:
    needs: Build
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
      - name: Deploy
        run: ./gradlew publish

      - name: Send email
        uses: devellany/send-mailer@v1.0.2
        with:
          host: smtp.google.com
          account: bendahmane.nesrine@gmail.com
          password: ${{secrets.MAIL_TOKEN}}
          sender: devellany
          from: bendahmane.nesrine@gmail.com
          to: ln_bendahmane@esi.dz
          subject: deploy succes.
          body: deploy project succes 
          contentType: text/html
      
